Plan rights model
meirim-org/meirim pull request #179
Opened 2020-02-11 19:57 UTC by boris-p

Still a work in progress.

We want to have the option to parse plan instruction pdf and store associated data.

2020-02-11 19:57 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meirim-org/meirim?pullRequest=179) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meirim-org/meirim?pullRequest=179) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meirim-org/meirim?pullRequest=179) it.</sub>

2020-02-26 08:05 UTC, dortheimer commented on api/lib/mavat/planInstructions/index.js
> +    if (files.length > 0){
What happens when `files` is 0?
Should this return faise?
If this is the case it's better to return false on the reverse condition and limit the nesting of the code.

2020-02-26 08:05 UTC, dortheimer commented on api/lib/mavat/planInstructions/index.js
> +        console.log('error getting files');
Should this return also false?

2020-02-26 08:06 UTC, dortheimer commented on api/lib/mavat/planInstructions/index.js
> +    }
The function should return true when successful and false if failed

2020-02-26 08:07 UTC, dortheimer commented on api/lib/mavat/planInstructions/parser/chartFive.js
> +  const DESIGNATION_COL = 11;
This may be a global scope variable?

2020-07-15 14:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meirim-org/meirim?pullRequest=179) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/meirim-org/meirim?pullRequest=179) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Tomer Laor<br/>:x: boris-p<br/><hr/>**Tomer Laor** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meirim-org/meirim?pullRequest=179) it.</sub>

2020-10-07 12:27 UTC, florpor requested changes
i wrote a lot of duplicate issues here just so they are listed.
important things for merge imo are:

1. change all `console.log` to `log.whatever` calls
2. add template function for row trimmer (in chartToArrayBuilder.js) so template doesn't need to know implementations
3. unify chart parser interface (separate process function should be called from within single interface function)
4. new table migrations should cascade on delete
5. remove plan_tag migration
6. remove files - api/lib/mavat/tmp/place_holder (what is it used for?) + boris_todo.md
7. remove old crawler download behaviour code

2020-10-16 19:16 UTC, TomerMe2 commented on api/lib/mavat/index.js
> +    fetch
bin/read_missing_pdfgs.js uses it to load specific plan pages

2020-10-16 20:13 UTC, TomerMe2 commented on api/model/plan.js
> +        const chartFourData = mavatData.chartFour;
It's not necessary, it's just for readability and comfort (writing mavatData.chartFour for 3 more time is not that comfortable).

2020-10-16 20:15 UTC, TomerMe2 commented on api/model/plan.js
> +                const chartFourRowData = chartFourData[i];
This copy can hurt performance since it's copying a string and not a pointer. I'll fix that, thanks :)

2020-10-16 20:35 UTC, TomerMe2 commented on bin/read_missing_pdfs.js
> +const mavat = require('../api/lib/mavat');
This script should be run in order to fill the db with data from the pdfs of the plans we got in our db. This script should be used once.

2020-10-16 20:43 UTC, TomerMe2 commented on api/model/plan.js
>  const Model = require("./base_model");
It was used to force git into indexing the empty "tmp" folder in the repo.
The code changed so it doesn't need this place holder anymore, I'll delete it.

2020-10-17 19:26 UTC, merged