New register flow
meirim-org/meirim pull request #231
Opened 2020-10-25 12:41 UTC by jbesraa

#217

2020-11-10 08:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meirim-org/meirim?pullRequest=231) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/meirim-org/meirim?pullRequest=231) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jbesraa<br/>:x: nadavmoreno<br/><hr/>**nadavmoreno** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meirim-org/meirim?pullRequest=231) it.</sub>

2020-11-17 19:53 UTC, florpor requested changes

2020-11-17 19:53 UTC, florpor commented on server/api/model/person.js
> +			type: ['required', 'string'],
will type be saved as the exact label shown to the user at frontend?
also, lets add backend validation for this field so we don't accept just any value

2020-11-18 18:35 UTC, jbesraa commented on .github/workflows/client.yml
> +                  $(npm bin)/cypress run --browser chrome --headless
the sign up fails in the second(firefox in this case) test because the user already exist in the db

2020-11-18 18:36 UTC, jbesraa commented on server/migrations/20201109095301_remove_firstName_and_lastName_from_person.js
> +exports.up = function(knex) {
not sure
want them all in the same file?

2020-11-18 18:37 UTC, jbesraa commented on client/src/shared/button/index.jsx
> +import React from 'react';
yea the future plan is to move these into components folder but atm I dont wanna mix old + new stuff

2020-11-18 19:51 UTC, florpor commented on server/migrations/20201109095301_remove_firstName_and_lastName_from_person.js
> +exports.up = function(knex) {
yeah, i think it's easier to follow changes and understand what is happening with the database that way

2020-11-18 19:55 UTC, florpor commented on .github/workflows/client.yml
> +                  $(npm bin)/cypress run --browser chrome --headless
can you generate an email based on the time / random in a `before` hook and use that?
if we remove firefox now we'll probably never test it and that would be a shame

2020-11-19 07:33 UTC, jbesraa commented on .github/workflows/client.yml
> +                  $(npm bin)/cypress run --browser chrome --headless
I need a valid email - how do I do that?
```const userEmail = `test.${Date.now()}@meirim.org```

this is invalid

2020-11-19 07:34 UTC, jbesraa commented on .github/workflows/client.yml
> +                  $(npm bin)/cypress run --browser chrome --headless
different option is to run them separately and clear the db before the second one

2020-11-19 08:22 UTC, florpor commented on .github/workflows/client.yml
> +                  $(npm bin)/cypress run --browser chrome --headless
yes i meant something like the `Date.now()` email - why is the above email invalid? seems to work with the (current) email verification lib

2020-11-23 08:56 UTC, jbesraa commented
@florpor nice1!

2020-11-23 09:06 UTC, florpor approved these changes

2020-11-23 09:07 UTC, merged