Test alert and comment models
meirim-org/meirim pull request #235
Opened 2020-10-26 14:06 UTC by nadavsofi

2020-10-26 14:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meirim-org/meirim?pullRequest=235) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meirim-org/meirim?pullRequest=235) before we can accept your contribution.<br/><hr/>**nadavmoreno** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meirim-org/meirim?pullRequest=235) it.</sub>

2020-10-26 18:24 UTC, jbesraa requested changes

2020-10-26 18:24 UTC, jbesraa commented on client/.gitignore
> +http-client/
is http-client part of the project?

2020-10-26 18:24 UTC, jbesraa commented on server/package.json
> +        "test": "NODE_ENV=test ./node_modules/.bin/mocha ./tests/integration/* ./tests/unit/* --exit --recursive --timeout 8000 --require ./tests/setup.js",
lets increase the timeout to 10000

2020-10-26 18:24 UTC, jbesraa commented on server/package.json
> +        "watch": "nodemon bin/api"
use project path, so: ./node_modules/.bin/nodemon bin/api

2020-10-26 18:24 UTC, jbesraa commented on server/tests/docker-compose.yml
> +version: '3.6'
I would add some text on the of the top of this file to explain what its used for..

2020-10-31 14:07 UTC, nadavsofi commented on client/.gitignore
> +http-client/
not anymore

2020-11-21 15:21 UTC, jbesraa commented
@nadavsofi  can you please update this PR?

2020-11-23 17:12 UTC, jbesraa approved these changes

2020-11-23 17:12 UTC, jbesraa commented
@florpor this is good to go. nothing special here

2020-11-24 08:04 UTC, merged