add kkl permits
meirim-org/meirim pull request #335
Opened 2021-02-07 08:12 UTC by gruppin

2021-02-07 19:26 UTC, florpor requested changes

2021-02-07 19:26 UTC, florpor commented on server/api/lib/trees/regional_tree_permit.js
> +		const compact_tp = `${tp.attributes[tpc.REGIONAL_OFFICE]}_${tp.attributes[tpc.PERMIT_NUMBER]}_${formatDate(tp.attributes[tpc.START_DATE], MORNING, 'YYYY-MM-DD')}`;
should add 'YYYY-MM-DD' to line 109 for existing permit key maybe?

2021-02-07 19:26 UTC, florpor commented on server/api/model/tree_permit_constants.js
> +exports.UNSUPPORTED_PLACES = [
what is unsupported places?

2021-02-07 19:26 UTC, florpor commented on server/api/lib/trees/regional_tree_permit.js
> +const getValueBySheetName = (row, tree_permit_field, sheetName) => {
let's discuss splitting this to separate crawler modules for the next places we will hopefully crawl :)

2021-02-11 21:21 UTC, nonZero commented
Hi!

I have a built a small python parser for these docs:
https://github.com/hasadna/israel_tree_removal_permit_scraper/blob/master/doc_parser.py
I don't know if this is useful - but I'll be happy to help with anything (more formats?) if you need.

You can see somewhat normalized results here:
https://github.com/hasadna/israel_tree_removal_permits_csv
and here:
https://github.com/hasadna/israel_tree_removal_permits_csv

Cheers!
Udi

2021-02-19 09:37 UTC, merged