File crawling for plans
meirim-org/meirim pull request #353
Opened 2021-04-24 18:46 UTC by GalGend

This PR is only for crawlign and saving mavat files

2021-04-24 18:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meirim-org/meirim?pullRequest=353) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meirim-org/meirim?pullRequest=353) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meirim-org/meirim?pullRequest=353) it.</sub>

2021-04-24 18:49 UTC, GalGend commented on server/api/lib/mavat/files/index.js
> +    if (isKML3d(file)) return 'kml';
Here I should change to use the enum

2021-04-27 21:33 UTC, florpor requested changes
see comments above, and also please add a basic test for this (can be part of the existing crawler tests) so we know it works (at least basically) through package upgrades and code changes.

2021-04-27 21:33 UTC, florpor commented on server/api/lib/mavat/index.js
> +			//return fetch(plan.plan_url);
remove comment

2021-04-27 21:33 UTC, florpor commented on server/api/lib/mavat/files/index.js
> +const { File } = require('../../../model');
file model is not exported at `api/model/index.js`. either do that or change this require

2021-06-01 21:23 UTC, florpor approved these changes

2021-06-03 19:16 UTC, merged